spring:
    datasource:
      url: jdbc:mysql://208.87.207.117:3306/shirodemo?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
      username: root
      password: root
      #172.17.0.1:3306
      #schema: database/import.sql
      #sql-script-encoding: utf-8
      driver-class-name: com.mysql.cj.jdbc.Driver

    jpa:
      database: mysql
      show-sql: true
      hibernate:
        ddl-auto: update
      properties:
         hibernate:
            dialect: org.hibernate.dialect.MySQL5Dialect

    thymeleaf:
       prefix: classpath:/templates/  #prefix：指定模板所在的目录
       #check-template-location: true  #check-tempate-location: 检查模板路径是否存在
       cache: false  #cache: 是否缓存，开发模式下设置为false，避免改了模板还要重启服务器，线上设置为true，可以提高性能。
       #suffix: .html
       #encoding: UTF-8
       #content-type: text/html
       mode: HTML